/**
  ******************************************************************************
  * File Name          : I2C.c
  * Description        : This file provides code for the configuration
  *                      of the I2C instances.
  ******************************************************************************
  ** This notice applies to portions of this file generated by CubeMx 
  * Other portions of this file, whether inserted by the user or by 
  * software development tools are owned by their respective copyright 
  * owners.
  *
  * COPYRIGHT(c) 2018 STMicroelectronics
  *
  * Redistribution and use in source and binary forms, with or without modification,
  * are permitted provided that the following conditions are met:
  *   1. Redistributions of source code must retain the above copyright notice,
  *      this list of conditions and the following disclaimer.
  *   2. Redistributions in binary form must reproduce the above copyright notice,
  *      this list of conditions and the following disclaimer in the documentation
  *      and/or other materials provided with the distribution.
  *   3. Neither the name of STMicroelectronics nor the names of its contributors
  *      may be used to endorse or promote products derived from this software
  *      without specific prior written permission.
  *
  * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
  * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
  * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
  * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
  * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
  * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
  * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
  * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
  * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
  * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
  *
  ******************************************************************************
  */

/* Includes ------------------------------------------------------------------*/
#include "i2c.h"
#include "uart.h"
#include "gpio.h"

HAL_StatusTypeDef read_reg(uint8_t reg_addr, uint8_t channel_addr, uint16_t *rsp) {

  // Select the internal register
  HAL_StatusTypeDef status = HAL_I2C_Master_Transmit(&hi2c1, channel_addr << 1, (uint8_t*) &reg_addr, sizeof(reg_addr), I2C_TIMEOUT); 

  if (status != HAL_OK) return status;

  // Read it
  status = HAL_I2C_Master_Receive(&hi2c1, channel_addr << 1, (uint8_t*) rsp, sizeof(*rsp), I2C_TIMEOUT);

  // Convert big endian to little endian
  *rsp = ((*rsp) << 8) | ((*rsp) >> 8);

  return status;
}

HAL_StatusTypeDef write_reg(uint8_t reg_addr, uint8_t channel_addr, uint16_t val) {
  
  uint8_t msg[3] = {reg_addr, val};
  return HAL_I2C_Master_Transmit(&hi2c1, channel_addr << 1, msg, sizeof(msg), I2C_TIMEOUT);
}

HAL_StatusTypeDef reset_channel(uint8_t channel_addr) {
  return write_reg(INA226_REG_CONF, channel_addr, 1 << 7);  // Set reset value to 1
}

HAL_StatusTypeDef read_current(uint8_t channel_addr, uint16_t* rsp) {
  return read_reg(INA226_REG_CURRENT, channel_addr, rsp);
}

HAL_StatusTypeDef read_voltage(uint8_t channel_addr, uint16_t* rsp) {
  return read_reg(INA226_REG_BUS_VOLT, channel_addr, rsp);
}

I2C_HandleTypeDef hi2c1;

/* I2C1 init function */
void MX_I2C1_Init(void)
{

  hi2c1.Instance = I2C1;
  hi2c1.Init.ClockSpeed = 100000;
  hi2c1.Init.DutyCycle = I2C_DUTYCYCLE_2;
  hi2c1.Init.OwnAddress1 = 0;
  hi2c1.Init.AddressingMode = I2C_ADDRESSINGMODE_7BIT;
  hi2c1.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
  hi2c1.Init.OwnAddress2 = 0;
  hi2c1.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
  hi2c1.Init.NoStretchMode = I2C_NOSTRETCH_DISABLE;
  if (HAL_I2C_Init(&hi2c1) != HAL_OK)
  {
    _Error_Handler(__FILE__, __LINE__);
  }

}

void HAL_I2C_MspInit(I2C_HandleTypeDef* i2cHandle)
{

  GPIO_InitTypeDef GPIO_InitStruct;
  if(i2cHandle->Instance==I2C1)
  {

    /** I2C1 GPIO Configuration    
    PB6     ------> I2C1_SCL
    PB7     ------> I2C1_SDA 
    */
    GPIO_InitStruct.Pin = GPIO_PIN_6|GPIO_PIN_7;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_OD;
    GPIO_InitStruct.Pull = GPIO_PULLUP;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
    GPIO_InitStruct.Alternate = GPIO_AF4_I2C1;
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);

    // I2C1 clock enable
    __HAL_RCC_I2C1_CLK_ENABLE();

  }
}

void HAL_I2C_MspDeInit(I2C_HandleTypeDef* i2cHandle)
{

  if(i2cHandle->Instance==I2C1)
  {

    // Peripheral clock disable
    __HAL_RCC_I2C1_CLK_DISABLE();
  
    /** I2C1 GPIO Configuration    
    PB6     ------> I2C1_SCL
    PB7     ------> I2C1_SDA 
    */
    HAL_GPIO_DeInit(GPIOB, GPIO_PIN_6|GPIO_PIN_7);

  }
} 
